### ISSUE TITLE
Update send_reports.php with horizontal scrolling and fixed sidebar overlay

### ISSUE THREAD

**Issue by Guram-jajanidze** [Guram-jajanidze/skills-copilot-codespaces-vscode#1]
## Overview
Update the send_reports.php file to improve user experience with horizontal scrolling functionality and fix the sidebar behavior to work as an overlay instead of pushing content.

### 1. Enable Horizontal Scroll Using Mouse
- Wrap entire form columns in a scrollable container
- Add CSS class `.form-scroll-container` with the following properties:
  ```css
  .form-scroll-container {
    overflow-x: auto;
    white-space: nowrap;
    scroll-behavior: smooth;
    display: flex;
    gap: 1rem;
    padding-bottom: 0.5rem;
  }
  .report-form {
    min-width: 300px;
    flex-shrink: 0;
  }
  ```
- Enable full horizontal scrolling across form columns using regular mouse (not just touchpad)

### 2. Fix Sidebar Overlay Behavior
- Sidebar should slide in as an overlay (position: fixed)
- Sidebar should NOT push or shift the form layout
- Add CSS styling for sidebar:
  ```css
  #sidebar {
    position: fixed;
    left: 0;
    top: 0;
    z-index: 50;
    width: 240px;
    height: 100vh;
    background-color: #f9fafb;
    transition: transform 0.3s ease-in-out;
    transform: translateX(-100%);
  }

  #sidebar.active {
    transform: translateX(0);
  }
  ```

### 3. JavaScript Toggle Functionality
- Add toggle button functionality for sidebar visibility
- Toggle should use `.active` class
- Main form container `#formContainer` should remain static (no movement)

### 4. HTML Layout Structure
Implement the following layout structure:
```html
<div id="sidebar">Sidebar content</div>
<div id="home-section">
  <button id="btn">Toggle Sidebar</button>
  <div id="formContainer" class="form-scroll-container">
    <div class="report-form">Form Section 1</div>
    <div class="report-form">Form Section 2</div>
    <!-- Add more columns as needed -->
  </div>
</div>
```

## Expected Outcomes
- ✅ Form is horizontally scrollable with both mouse and touchpad
- ✅ Sidebar appears with smooth animation without affecting layout
- ✅ Layout is clean, user-friendly, and responsive
- ✅ No content shifting when sidebar toggles

## Technical Notes
- Current file is a PHP file with existing functionality that needs to be preserved
- File includes form handling, email functionality, and database operations
- Changes should focus on frontend CSS/JS improvements without affecting backend logic

## Files Involved
- `send_reports.php` (main file to be updated)
- Related CSS and JavaScript files as needed
